/**
 * generated by v0 by Vercel
 * @see https://v0.dev/t/dxrLCFc1vMs
 */
import Link from "next/link";
import parse from "html-react-parser";
import Date from "./date";
import Avatar from "./avatar";
import CoverImage from "./cover-image";

export default function HeroSplit({
  title,
  coverImage,
  date,
  author,
  excerpt,
  slug,
}) {
  return (
    <div className="min-h-screen bg-white">
      <main className="hero hero--split">
        <div className="hero__copy">
          <div className="hero__copy__inner">
            <h2 className="pb-2 text-4xl text-gray-900">
              <Link href={`/posts/${slug}`} className="hover:underline">
                {title}
              </Link>
            </h2>
            <p className="pb-2 text-gray-500">
              <Date dateString={date} />
            </p>
            <div className="flex items-center space-x-4">
              {author && <Avatar author={author} />}
            </div>
            {excerpt && <div className="text-xl text-gray-900">{parse(excerpt)}</div>}
          </div>
        </div>
        {coverImage && (
          <CoverImage title={title} coverImage={coverImage} slug={slug} />
        )}
      </main>
    </div>
  );
}
