/**
 * generated by v0 by Vercel
 * @see https://v0.dev/t/dxrLCFc1vMs
 */
import cn from "classnames";
import Link from "next/link";
import Image from "next/image";
import parse from "html-react-parser";
import Date from "./date";
import Avatar from "./avatar";

export default function HeroSplit({
  title,
  coverImage,
  date,
  author,
  excerpt,
  slug,
}) {
  return (
    <div className="min-h-screen">
      <main className="hero hero--split">
        <div className="hero__copy">
          <div className="hero__copy__inner">
            <h1 className="text-gray-900">
              <Link href={`/posts/${slug}`} className="hover:underline">
                {title}
              </Link>
            </h1>
            <p className="post__date text-gray-500">
              <Date dateString={date} />
            </p>
            <div className="flex items-center space-x-4">
              {author && <Avatar author={author} />}
            </div>
            {excerpt && <div className="post__excerpt">{parse(excerpt)}</div>}
          </div>
        </div>
        {coverImage && (
          <div className="post__image--cover">
            <Image
              width={2000}
              height={2500}
              alt={`Cover Image for ${title}`}
              src={coverImage.node.sourceUrl}
              className={cn("shadow-small", {
                "hover:shadow-medium transition-shadow duration-200": slug,
              })}
            />
          </div>
        )}
      </main>
    </div>
  );
}
